version: '3.3'

services:
  lb-server:
    image: nginx:stable-alpine
    volumes:
      - ./lb-server/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 4
    ports:
      - "80:80"
    links:
      - cache-server
    networks:
      - front-tier
  
  cache-server:
    image: nginx:stable-alpine
    volumes:
      - ./cache-server/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 4
    expose: 
      - "8000"
    networks:
      - front-tier
      - back-tier

  origin-server:
    image: nginx:stable-alpine
    volumes:
      - ./origin-server/nginx.conf:/etc/nginx/nginx.conf:ro
      - /hosthome/users/wallace.figueiredo/:/usr/share/nginx/html:ro
      #- ~/.npm/:/usr/share/nginx/html:ro
    deploy:
      replicas: 2
    expose: 
      - "9000"
    networks:
      - back-tier

networks:
  front-tier:
    driver: overlay
  back-tier:
    driver: overlay